# IMPORTS

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from datetime import datetime

# FONCTIONS

# DATAFRAME PATH - SET UP

In [2]:
#Chemin pour revenir aux directories de base
path_init = "../../../"

#Rejoindre les dataframe créés pour l'APP et dans lesquels on trouve des données manuelles
to_APP_data = "MVP APP/DATAFRAMES/MVP_setup_dataframes/march/filtered/"
# os.listdir(path_init+to_APP_data)

#Rejoindre les données du MetTripod
to_MET_data = "SAJESS/SJ_Met_Tripod/"
# os.listdir(path_init+to_MET_data)

## Dataframes des tempêtes de mars

In [3]:
#---
# On va chercher les df des tempêtes 0 à 4 de mars
# Chacun dans une variable distincte.
#---

# Colonnes à conserver
columns = ['timestamp','file', 'hydrometeor', 'radio variable', 'saves', 'label ID ','xhi ','fallspeed ']

### Filtered dataframes

In [4]:
# Tempête 0
t0_file = "filtered_march_storm00_df.csv"
tempete_0 = pd.read_csv(path_init+to_APP_data+t0_file)[columns]
tempete_0.index=pd.to_datetime(tempete_0['timestamp'])
tempete_0 = tempete_0.drop('timestamp', axis=1)


tempete_0

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed
timestamp,,,,,,,
2021-03-09 12:25:16,2021.03.09_12.25.16_flake_1_cam_0.png,Aggregate,0,1,4,10.4260,NaN
2021-03-09 12:25:23,2021.03.09_12.25.23_flake_3_cam_0.png,Aucune Sélection,1,1,3,9.2167,1.16810
2021-03-09 12:25:23,2021.03.09_12.25.23_flake_3_cam_2.png,Aucune Sélection,1,1,3,10.8100,1.16810
2021-03-09 12:25:33,2021.03.09_12.25.33_flake_6_cam_0.png,Aggregate,0,1,4,10.2650,1.11150
2021-03-09 12:25:33,2021.03.09_12.25.33_flake_6_cam_2.png,Aucune Sélection,1,1,3,10.2550,1.11150
...,...,...,...,...,...,...,...
2021-03-09 20:23:44,2021.03.09_20.23.44_flake_121_cam_0.png,Aggregate,0,1,3,10.6590,0.48704
2021-03-09 20:27:28,2021.03.09_20.27.28_flake_123_cam_0.png,Aggregate,0,1,4,9.5623,0.65395
2021-03-09 20:27:28,2021.03.09_20.27.28_flake_123_cam_2.png,Aggregate,0,1,4,9.0658,0.65395
2021-03-09 20:27:34,2021.03.09_20.27.34_flake_124_cam_0.png,Aggregate,0,1,4,10.3900,0.84530
2021-03-09 20:27:34,2021.03.09_20.27.34_flake_124_cam_2.png,NaN,0,0,4,9.1622,0.84530

In [5]:
# Tempête 1
t1_file = "filtered_march_storm01_df.csv"
tempete_1 = pd.read_csv(path_init+to_APP_data+t1_file)[columns]
tempete_1.index = pd.to_datetime(tempete_1['timestamp'])
tempete_1 = tempete_1.drop('timestamp', axis=1)

tempete_1

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed
timestamp,,,,,,,
2021-03-13 07:29:37,2021.03.13_07.29.37_flake_443_cam_0.png,NaN,0,0,1,9.4466,0.081312
2021-03-13 07:29:37,2021.03.13_07.29.37_flake_443_cam_1.png,NaN,0,0,1,9.2257,0.081312
2021-03-13 07:29:37,2021.03.13_07.29.37_flake_443_cam_2.png,NaN,0,0,1,9.6345,0.081312
2021-03-13 07:43:52,2021.03.13_07.43.52_flake_444_cam_0.png,NaN,0,0,4,10.3460,1.042300

In [6]:
# Tempête 2
t2_file = "filtered_march_storm02_df.csv"
tempete_2 = pd.read_csv(path_init+to_APP_data+t2_file)[columns]
tempete_2.index = pd.to_datetime(tempete_2['timestamp'])
tempete_2 = tempete_2.drop('timestamp', axis=1)

tempete_2

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed
timestamp,,,,,,,
2021-03-14 10:04:14,2021.03.14_10.04.14_flake_537_cam_0.png,Aggregate,0,1,5,9.2434,0.70068
2021-03-14 10:04:14,2021.03.14_10.04.14_flake_537_cam_2.png,Aggregate,0,1,5,9.7071,0.70068
2021-03-14 10:05:41,2021.03.14_10.05.41_flake_541_cam_0.png,Aggregate,0,1,4,9.4362,NaN
2021-03-14 10:05:41,2021.03.14_10.05.41_flake_541_cam_2.png,Aggregate,0,1,4,10.8180,NaN
2021-03-14 10:07:17,2021.03.14_10.07.17_flake_542_cam_0.png,Aggregate,0,1,5,9.3618,0.51623
...,...,...,...,...,...,...,...
2021-03-14 11:06:36,2021.03.14_11.06.36_flake_608_cam_0.png,Aggregate,0,1,5,9.5434,0.75170
2021-03-14 11:06:36,2021.03.14_11.06.36_flake_608_cam_2.png,Aggregate,0,1,2,9.7278,0.75170
2021-03-14 11:11:40,2021.03.14_11.11.40_flake_609_cam_2.png,Aggregate,0,1,4,10.3510,0.80537
2021-03-14 11:12:07,2021.03.14_11.12.07_flake_610_cam_2.png,Aggregate,0,1,3,10.1070,0.82895
2021-03-14 11:14:48,2021.03.14_11.14.48_flake_611_cam_0.png,NaN,0,0,1,9.7797,1.07230

In [7]:
# Tempête 3
t3_file = "filtered_march_storm03_df.csv"
tempete_3 = pd.read_csv(path_init+to_APP_data+t3_file)[columns]
tempete_3.index = pd.to_datetime(tempete_3['timestamp'])
tempete_3 = tempete_3.drop('timestamp', axis=1)

tempete_3

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed
timestamp,,,,,,,
2021-03-27 02:18:45,2021.03.27_02.18.45_flake_3772_cam_0.png,Aucune Sélection,1,1,1,9.0964,0.16020
2021-03-27 02:18:45,2021.03.27_02.18.45_flake_3772_cam_2.png,NaN,0,1,1,9.1816,0.16020
2021-03-27 02:21:21,2021.03.27_02.21.21_flake_3773_cam_0.png,Aggregate,0,1,4,9.2676,2.80600
2021-03-27 02:21:21,2021.03.27_02.21.21_flake_3773_cam_1.png,Aggregate,0,1,4,9.5605,2.80600
2021-03-27 02:21:21,2021.03.27_02.21.21_flake_3773_cam_2.png,Aggregate,0,1,4,9.0488,2.80600
...,...,...,...,...,...,...,...
2021-03-27 09:02:47,2021.03.27_09.02.47_flake_6717_cam_1.png,Aggregate,0,1,4,10.2960,0.87182
2021-03-27 09:02:47,2021.03.27_09.02.47_flake_6717_cam_2.png,NaN,0,0,4,9.4255,0.87182
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_0.png,NaN,0,0,4,10.6690,0.92324
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_1.png,NaN,0,0,4,10.5100,0.92324
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_2.png,NaN,0,0,4,10.2180,0.92324

In [8]:
# Tempête 4
t4_file = "filtered_march_storm04_df.csv"
tempete_4 = pd.read_csv(path_init+to_APP_data+t4_file)[columns]
tempete_4.index = pd.to_datetime(tempete_4['timestamp'])
tempete_4 = tempete_4.drop('timestamp', axis=1)

tempete_4

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed
timestamp,,,,,,,
2021-03-28 14:33:09,2021.03.28_14.33.09_flake_6753_cam_0.png,Aggregate,0,1,5,9.9952,0.084466
2021-03-28 14:33:09,2021.03.28_14.33.09_flake_6753_cam_1.png,Graupel,0,1,5,9.2024,0.084466
2021-03-28 14:33:09,2021.03.28_14.33.09_flake_6753_cam_2.png,Graupel,0,1,5,10.0430,0.084466
2021-03-28 14:36:08,2021.03.28_14.36.08_flake_6755_cam_0.png,Graupel,0,1,5,10.1720,1.583900
2021-03-28 14:36:08,2021.03.28_14.36.08_flake_6755_cam_1.png,Graupel,0,1,5,9.9375,1.583900
...,...,...,...,...,...,...,...
2021-03-29 18:20:29,2021.03.29_18.20.29_flake_4814_cam_2.png,NaN,0,0,5,9.7379,0.085907
2021-03-29 18:25:12,2021.03.29_18.25.12_flake_4816_cam_1.png,NaN,0,0,5,9.0082,0.109680
2021-03-29 18:25:12,2021.03.29_18.25.12_flake_4816_cam_2.png,NaN,0,0,5,9.8941,0.109680
2021-03-29 18:35:25,2021.03.29_18.35.25_flake_4820_cam_0.png,NaN,0,0,5,9.1147,1.284400
2021-03-29 19:07:23,2021.03.29_19.07.23_flake_4822_cam_2.png,NaN,0,0,1,10.4970,1.995000

## Dataframes des données du MetTripod

In [9]:
#---
# Dans les observations, on utilise le fichier "detailed_obs_summary.txt",
# qui donne les débuts et fin des tempêtes, avec les types de précipitations principaux observés.
#---
Met_Tripod = pd.read_csv(path_init+to_MET_data+"SJ_MT_MET_01_MAS_1min_202103.txt")
Met_Tripod.set_index("Timestamp", inplace=True)

Met_Tripod.index = pd.to_datetime(Met_Tripod.index)

#On ne conserve que les colonnes utiles pour les petits résultats recherchés.
Met_Tripod_rdx=Met_Tripod[['Humidity','Air_Temp']]

Met_Tripod_rdx

                     Humidity  Air_Temp
Timestamp
2021-03-01 00:00:00       NaN       NaN
2021-03-01 00:01:00       NaN       NaN
2021-03-01 00:02:00       NaN       NaN
2021-03-01 00:03:00       NaN       NaN
2021-03-01 00:04:00       NaN       NaN
...                       ...       ...
2021-03-31 23:55:00     75.91  10.77034
2021-03-31 23:56:00     75.72  10.76974
2021-03-31 23:57:00     75.51  10.75570
2021-03-31 23:58:00     76.20  10.67770
2021-03-31 23:59:00     76.51  10.57459

[44640 rows x 2 columns]

## Jointure des données à la minute entre "Met_Tripod_rdx" et les "tempete_x"

In [10]:
# Tempête 0

tempete_0.index = tempete_0.index.floor('T')

# Step 2: Join based on the aligned indices
tempete_0 = tempete_0.join(Met_Tripod_rdx[['Air_Temp', 'Humidity']], how='left')

tempete_0

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity
2021-03-09 12:25:00,2021.03.09_12.25.16_flake_1_cam_0.png,Aggregate,0,1,4,10.4260,NaN,-15.410800,84.10
2021-03-09 12:25:00,2021.03.09_12.25.23_flake_3_cam_0.png,Aucune Sélection,1,1,3,9.2167,1.16810,-15.410800,84.10
2021-03-09 12:25:00,2021.03.09_12.25.23_flake_3_cam_2.png,Aucune Sélection,1,1,3,10.8100,1.16810,-15.410800,84.10
2021-03-09 12:25:00,2021.03.09_12.25.33_flake_6_cam_0.png,Aggregate,0,1,4,10.2650,1.11150,-15.410800,84.10
2021-03-09 12:25:00,2021.03.09_12.25.33_flake_6_cam_2.png,Aucune Sélection,1,1,3,10.2550,1.11150,-15.410800,84.10
...,...,...,...,...,...,...,...,...,...
2021-03-09 20:23:00,2021.03.09_20.23.44_flake_121_cam_0.png,Aggregate,0,1,3,10.6590,0.48704,-2.486949,75.06
2021-03-09 20:27:00,2021.03.09_20.27.28_flake_123_cam_0.png,Aggregate,0,1,4,9.5623,0.65395,-2.432562,74.78
2021-03-09 20:27:00,2021.03.09_20.27.28_flake_123_cam_2.png,Aggregate,0,1,4,9.0658,0.65395,-2.432562,74.78
2021-03-09 20:27:00,2021.03.09_20.27.34_flake_124_cam_0.png,Aggregate,0,1,4,10.3900,0.84530,-2.432562,74.78
2021-03-09 20:27:00,2021.03.09_20.27.34_flake_124_cam_2.png,NaN,0,0,4,9.1622,0.84530,-2.432562,74.78

In [11]:
# Tempête 1
tempete_1.index = tempete_1.index.floor('T')

# Step 2: Join based on the aligned indices
tempete_1 = tempete_1.join(Met_Tripod_rdx[['Air_Temp', 'Humidity']], how='left')

tempete_1

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity
2021-03-13 07:29:00,2021.03.13_07.29.37_flake_443_cam_0.png,NaN,0,0,1,9.4466,0.081312,-2.701553,61.23
2021-03-13 07:29:00,2021.03.13_07.29.37_flake_443_cam_1.png,NaN,0,0,1,9.2257,0.081312,-2.701553,61.23
2021-03-13 07:29:00,2021.03.13_07.29.37_flake_443_cam_2.png,NaN,0,0,1,9.6345,0.081312,-2.701553,61.23
2021-03-13 07:43:00,2021.03.13_07.43.52_flake_444_cam_0.png,NaN,0,0,4,10.3460,1.042300,-2.930646,60.58

In [12]:
# Tempête 2
tempete_2.index = tempete_2.index.floor('T')

# Step 2: Join based on the aligned indices
tempete_2 = tempete_2.join(Met_Tripod_rdx[['Air_Temp', 'Humidity']], how='left')

tempete_2

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity
2021-03-14 10:04:00,2021.03.14_10.04.14_flake_537_cam_0.png,Aggregate,0,1,5,9.2434,0.70068,-10.04204,79.15
2021-03-14 10:04:00,2021.03.14_10.04.14_flake_537_cam_2.png,Aggregate,0,1,5,9.7071,0.70068,-10.04204,79.15
2021-03-14 10:05:00,2021.03.14_10.05.41_flake_541_cam_0.png,Aggregate,0,1,4,9.4362,NaN,-10.06263,78.97
2021-03-14 10:05:00,2021.03.14_10.05.41_flake_541_cam_2.png,Aggregate,0,1,4,10.8180,NaN,-10.06263,78.97
2021-03-14 10:07:00,2021.03.14_10.07.17_flake_542_cam_0.png,Aggregate,0,1,5,9.3618,0.51623,-10.09344,78.34
...,...,...,...,...,...,...,...,...,...
2021-03-14 11:06:00,2021.03.14_11.06.36_flake_608_cam_0.png,Aggregate,0,1,5,9.5434,0.75170,-10.32510,79.83
2021-03-14 11:06:00,2021.03.14_11.06.36_flake_608_cam_2.png,Aggregate,0,1,2,9.7278,0.75170,-10.32510,79.83
2021-03-14 11:11:00,2021.03.14_11.11.40_flake_609_cam_2.png,Aggregate,0,1,4,10.3510,0.80537,-10.35527,79.02
2021-03-14 11:12:00,2021.03.14_11.12.07_flake_610_cam_2.png,Aggregate,0,1,3,10.1070,0.82895,-10.35621,78.87
2021-03-14 11:14:00,2021.03.14_11.14.48_flake_611_cam_0.png,NaN,0,0,1,9.7797,1.07230,-10.36034,79.59

In [13]:
# Tempête 3
tempete_3.index = tempete_3.index.floor('T')

# Step 2: Join based on the aligned indices
tempete_3 = tempete_3.join(Met_Tripod_rdx[['Air_Temp', 'Humidity']], how='left')

tempete_3

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity
2021-03-27 02:18:00,2021.03.27_02.18.45_flake_3772_cam_0.png,Aucune Sélection,1,1,1,9.0964,0.16020,1.365920,91.1
2021-03-27 02:18:00,2021.03.27_02.18.45_flake_3772_cam_2.png,NaN,0,1,1,9.1816,0.16020,1.365920,91.1
2021-03-27 02:21:00,2021.03.27_02.21.21_flake_3773_cam_0.png,Aggregate,0,1,4,9.2676,2.80600,1.236691,92.3
2021-03-27 02:21:00,2021.03.27_02.21.21_flake_3773_cam_1.png,Aggregate,0,1,4,9.5605,2.80600,1.236691,92.3
2021-03-27 02:21:00,2021.03.27_02.21.21_flake_3773_cam_2.png,Aggregate,0,1,4,9.0488,2.80600,1.236691,92.3
...,...,...,...,...,...,...,...,...,...
2021-03-27 09:02:00,2021.03.27_09.02.47_flake_6717_cam_1.png,Aggregate,0,1,4,10.2960,0.87182,-2.687584,90.6
2021-03-27 09:02:00,2021.03.27_09.02.47_flake_6717_cam_2.png,NaN,0,0,4,9.4255,0.87182,-2.687584,90.6
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_0.png,NaN,0,0,4,10.6690,0.92324,-2.714185,90.5
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_1.png,NaN,0,0,4,10.5100,0.92324,-2.714185,90.5
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_2.png,NaN,0,0,4,10.2180,0.92324,-2.714185,90.5

In [14]:
# Tempête 4
tempete_4.index = tempete_4.index.floor('T')

# Step 2: Join based on the aligned indices
tempete_4 = tempete_4.join(Met_Tripod_rdx[['Air_Temp', 'Humidity']], how='left')

tempete_4

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity
2021-03-28 14:33:00,2021.03.28_14.33.09_flake_6753_cam_0.png,Aggregate,0,1,5,9.9952,0.084466,-2.984813,85.00
2021-03-28 14:33:00,2021.03.28_14.33.09_flake_6753_cam_1.png,Graupel,0,1,5,9.2024,0.084466,-2.984813,85.00
2021-03-28 14:33:00,2021.03.28_14.33.09_flake_6753_cam_2.png,Graupel,0,1,5,10.0430,0.084466,-2.984813,85.00
2021-03-28 14:36:00,2021.03.28_14.36.08_flake_6755_cam_0.png,Graupel,0,1,5,10.1720,1.583900,-2.941003,84.80
2021-03-28 14:36:00,2021.03.28_14.36.08_flake_6755_cam_1.png,Graupel,0,1,5,9.9375,1.583900,-2.941003,84.80
...,...,...,...,...,...,...,...,...,...
2021-03-29 18:20:00,2021.03.29_18.20.29_flake_4814_cam_2.png,NaN,0,0,5,9.7379,0.085907,-0.845398,74.49
2021-03-29 18:25:00,2021.03.29_18.25.12_flake_4816_cam_1.png,NaN,0,0,5,9.0082,0.109680,-0.803401,71.86
2021-03-29 18:25:00,2021.03.29_18.25.12_flake_4816_cam_2.png,NaN,0,0,5,9.8941,0.109680,-0.803401,71.86
2021-03-29 18:35:00,2021.03.29_18.35.25_flake_4820_cam_0.png,NaN,0,0,5,9.1147,1.284400,-0.695998,67.64
2021-03-29 19:07:00,2021.03.29_19.07.23_flake_4822_cam_2.png,NaN,0,0,1,10.4970,1.995000,-0.523494,61.34

In [15]:
#Fonction de numérisation des labels, pour les datafrane

def hm_to_label(hm):
    hm_list = ['Small particle',
                   'Columnar crystal',
                   'Planar crystal',
                   'Columnar/Planar crystals',
                   'Aggregate',
                   'Graupel',
                   'None']
    try:
        #On donne le label propre à une catégorie
        manual_label=hm_list.index(hm)+1
    except:
        #Dans les instances NaN, on veut le label None (7)
        manual_label=7
    return manual_label

In [16]:
# Fonction de filtre des images corrompues. Renvoie un dataframe sans les images corrompues, 
# et seulement avec les images classées (Save=1)
def complete_filter(df):
    return df[(df['radio variable'] == 0) &
              (df['saves'] == 1) &
              (df['manual ID'].isin([1,2,3,4,5,6]))]

In [17]:
tempetes=[tempete_0,tempete_1, tempete_2, tempete_3, tempete_4]
# Boucle de traitement
for i in range(len(tempetes)):
    tempetes[i]['manual ID'] = tempetes[i]['hydrometeor'].apply(hm_to_label)

# Afficher le résultat
for t in tempetes:
    print(t)

                                                         file  \
2021-03-09 12:25:00    2021.03.09_12.25.16_flake_1_cam_0.png
2021-03-09 12:25:00    2021.03.09_12.25.23_flake_3_cam_0.png
2021-03-09 12:25:00    2021.03.09_12.25.23_flake_3_cam_2.png
2021-03-09 12:25:00    2021.03.09_12.25.33_flake_6_cam_0.png
2021-03-09 12:25:00    2021.03.09_12.25.33_flake_6_cam_2.png
...                                                       ...
2021-03-09 20:23:00  2021.03.09_20.23.44_flake_121_cam_0.png
2021-03-09 20:27:00  2021.03.09_20.27.28_flake_123_cam_0.png
2021-03-09 20:27:00  2021.03.09_20.27.28_flake_123_cam_2.png
2021-03-09 20:27:00  2021.03.09_20.27.34_flake_124_cam_0.png
2021-03-09 20:27:00  2021.03.09_20.27.34_flake_124_cam_2.png

                          hydrometeor  radio variable  saves  label ID   \
2021-03-09 12:25:00         Aggregate               0      1          4
2021-03-09 12:25:00  Aucune Sélection               1      1          3
2021-03-09 12:25:00  Aucune Sélection               1      1          3
2021-03-09 12:25:00         Aggregate               0      1          4
2021-03-09 12:25:00  Aucune Sélection               1      1          3
...                               ...             ...    ...        ...
2021-03-09 20:23:00         Aggregate               0      1          3
2021-03-09 20:27:00         Aggregate               0      1          4
2021-03-09 20:27:00         Aggregate               0      1          4
2021-03-09 20:27:00         Aggregate               0      1          4
2021-03-09 20:27:00               NaN               0      0          4

                        xhi   fallspeed    Air_Temp  Humidity  manual ID
2021-03-09 12:25:00  10.4260         NaN -15.410800     84.10          5
2021-03-09 12:25:00   9.2167     1.16810 -15.410800     84.10          7
2021-03-09 12:25:00  10.8100     1.16810 -15.410800     84.10          7
2021-03-09 12:25:00  10.2650     1.11150 -15.410800     84.10          5
2021-03-09 12:25:00  10.2550     1.11150 -15.410800     84.10          7
...                      ...         ...        ...       ...        ...
2021-03-09 20:23:00  10.6590     0.48704  -2.486949     75.06          5
2021-03-09 20:27:00   9.5623     0.65395  -2.432562     74.78          5
2021-03-09 20:27:00   9.0658     0.65395  -2.432562     74.78          5
2021-03-09 20:27:00  10.3900     0.84530  -2.432562     74.78          5
2021-03-09 20:27:00   9.1622     0.84530  -2.432562     74.78          7

[873 rows x 10 columns]
                                                         file  hydrometeor  \
2021-03-13 07:29:00  2021.03.13_07.29.37_flake_443_cam_0.png           NaN
2021-03-13 07:29:00  2021.03.13_07.29.37_flake_443_cam_1.png           NaN
2021-03-13 07:29:00  2021.03.13_07.29.37_flake_443_cam_2.png           NaN
2021-03-13 07:43:00  2021.03.13_07.43.52_flake_444_cam_0.png           NaN

                     radio variable  saves  label ID      xhi   fallspeed   \
2021-03-13 07:29:00               0      0          1   9.4466    0.081312
2021-03-13 07:29:00               0      0          1   9.2257    0.081312
2021-03-13 07:29:00               0      0          1   9.6345    0.081312
2021-03-13 07:43:00               0      0          4  10.3460    1.042300

                     Air_Temp  Humidity  manual ID
2021-03-13 07:29:00 -2.701553     61.23          7
2021-03-13 07:29:00 -2.701553     61.23          7
2021-03-13 07:29:00 -2.701553     61.23          7
2021-03-13 07:43:00 -2.930646     60.58          7
                                                         file hydrometeor  \
2021-03-14 10:04:00  2021.03.14_10.04.14_flake_537_cam_0.png    Aggregate
2021-03-14 10:04:00  2021.03.14_10.04.14_flake_537_cam_2.png    Aggregate
2021-03-14 10:05:00  2021.03.14_10.05.41_flake_541_cam_0.png    Aggregate
2021-03-14 10:05:00  2021.03.14_10.05.41_flake_541_cam_2.png    Aggregate
2021-03-14 10:07:00  2021.03.14_10.07.17_flake_542_cam_0.png    Aggregate
...                                                       ...         ...
2021-03-14 11:06:00  2021.03.14_11.06.36_flake_608_cam_0.png    Aggregate
2021-03-14 11:06:00  2021.03.14_11.06.36_flake_608_cam_2.png    Aggregate
2021-03-14 11:11:00  2021.03.14_11.11.40_flake_609_cam_2.png    Aggregate
2021-03-14 11:12:00  2021.03.14_11.12.07_flake_610_cam_2.png    Aggregate
2021-03-14 11:14:00  2021.03.14_11.14.48_flake_611_cam_0.png          NaN

                     radio variable  saves  label ID      xhi   fallspeed   \
2021-03-14 10:04:00               0      1          5   9.2434     0.70068
2021-03-14 10:04:00               0      1          5   9.7071     0.70068
2021-03-14 10:05:00               0      1          4   9.4362         NaN
2021-03-14 10:05:00               0      1          4  10.8180         NaN
2021-03-14 10:07:00               0      1          5   9.3618     0.51623
...                             ...    ...        ...      ...         ...
2021-03-14 11:06:00               0      1          5   9.5434     0.75170
2021-03-14 11:06:00               0      1          2   9.7278     0.75170
2021-03-14 11:11:00               0      1          4  10.3510     0.80537
2021-03-14 11:12:00               0      1          3  10.1070     0.82895
2021-03-14 11:14:00               0      0          1   9.7797     1.07230

                     Air_Temp  Humidity  manual ID
2021-03-14 10:04:00 -10.04204     79.15          5
2021-03-14 10:04:00 -10.04204     79.15          5
2021-03-14 10:05:00 -10.06263     78.97          5
2021-03-14 10:05:00 -10.06263     78.97          5
2021-03-14 10:07:00 -10.09344     78.34          5
...                       ...       ...        ...
2021-03-14 11:06:00 -10.32510     79.83          5
2021-03-14 11:06:00 -10.32510     79.83          5
2021-03-14 11:11:00 -10.35527     79.02          5
2021-03-14 11:12:00 -10.35621     78.87          5
2021-03-14 11:14:00 -10.36034     79.59          7

[76 rows x 10 columns]
                                                          file  \
2021-03-27 02:18:00  2021.03.27_02.18.45_flake_3772_cam_0.png
2021-03-27 02:18:00  2021.03.27_02.18.45_flake_3772_cam_2.png
2021-03-27 02:21:00  2021.03.27_02.21.21_flake_3773_cam_0.png
2021-03-27 02:21:00  2021.03.27_02.21.21_flake_3773_cam_1.png
2021-03-27 02:21:00  2021.03.27_02.21.21_flake_3773_cam_2.png
...                                                        ...
2021-03-27 09:02:00  2021.03.27_09.02.47_flake_6717_cam_1.png
2021-03-27 09:02:00  2021.03.27_09.02.47_flake_6717_cam_2.png
2021-03-27 09:04:00  2021.03.27_09.04.00_flake_6718_cam_0.png
2021-03-27 09:04:00  2021.03.27_09.04.00_flake_6718_cam_1.png
2021-03-27 09:04:00  2021.03.27_09.04.00_flake_6718_cam_2.png

                          hydrometeor  radio variable  saves  label ID   \
2021-03-27 02:18:00  Aucune Sélection               1      1          1
2021-03-27 02:18:00               NaN               0      1          1
2021-03-27 02:21:00         Aggregate               0      1          4
2021-03-27 02:21:00         Aggregate               0      1          4
2021-03-27 02:21:00         Aggregate               0      1          4
...                               ...             ...    ...        ...
2021-03-27 09:02:00         Aggregate               0      1          4
2021-03-27 09:02:00               NaN               0      0          4
2021-03-27 09:04:00               NaN               0      0          4
2021-03-27 09:04:00               NaN               0      0          4
2021-03-27 09:04:00               NaN               0      0          4

                        xhi   fallspeed   Air_Temp  Humidity  manual ID
2021-03-27 02:18:00   9.0964     0.16020  1.365920      91.1          7
2021-03-27 02:18:00   9.1816     0.16020  1.365920      91.1          7
2021-03-27 02:21:00   9.2676     2.80600  1.236691      92.3          5
2021-03-27 02:21:00   9.5605     2.80600  1.236691      92.3          5
2021-03-27 02:21:00   9.0488     2.80600  1.236691      92.3          5
...                      ...         ...       ...       ...        ...
2021-03-27 09:02:00  10.2960     0.87182 -2.687584      90.6          5
2021-03-27 09:02:00   9.4255     0.87182 -2.687584      90.6          7
2021-03-27 09:04:00  10.6690     0.92324 -2.714185      90.5          7
2021-03-27 09:04:00  10.5100     0.92324 -2.714185      90.5          7
2021-03-27 09:04:00  10.2180     0.92324 -2.714185      90.5          7

[3606 rows x 10 columns]
                                                          file hydrometeor  \
2021-03-28 14:33:00  2021.03.28_14.33.09_flake_6753_cam_0.png    Aggregate
2021-03-28 14:33:00  2021.03.28_14.33.09_flake_6753_cam_1.png      Graupel
2021-03-28 14:33:00  2021.03.28_14.33.09_flake_6753_cam_2.png      Graupel
2021-03-28 14:36:00  2021.03.28_14.36.08_flake_6755_cam_0.png      Graupel
2021-03-28 14:36:00  2021.03.28_14.36.08_flake_6755_cam_1.png      Graupel
...                                                        ...         ...
2021-03-29 18:20:00  2021.03.29_18.20.29_flake_4814_cam_2.png          NaN
2021-03-29 18:25:00  2021.03.29_18.25.12_flake_4816_cam_1.png          NaN
2021-03-29 18:25:00  2021.03.29_18.25.12_flake_4816_cam_2.png          NaN
2021-03-29 18:35:00  2021.03.29_18.35.25_flake_4820_cam_0.png          NaN
2021-03-29 19:07:00  2021.03.29_19.07.23_flake_4822_cam_2.png          NaN

                     radio variable  saves  label ID      xhi   fallspeed   \
2021-03-28 14:33:00               0      1          5   9.9952    0.084466
2021-03-28 14:33:00               0      1          5   9.2024    0.084466
2021-03-28 14:33:00               0      1          5  10.0430    0.084466
2021-03-28 14:36:00               0      1          5  10.1720    1.583900
2021-03-28 14:36:00               0      1          5   9.9375    1.583900
...                             ...    ...        ...      ...         ...
2021-03-29 18:20:00               0      0          5   9.7379    0.085907
2021-03-29 18:25:00               0      0          5   9.0082    0.109680
2021-03-29 18:25:00               0      0          5   9.8941    0.109680
2021-03-29 18:35:00               0      0          5   9.1147    1.284400
2021-03-29 19:07:00               0      0          1  10.4970    1.995000

                     Air_Temp  Humidity  manual ID
2021-03-28 14:33:00 -2.984813     85.00          5
2021-03-28 14:33:00 -2.984813     85.00          6
2021-03-28 14:33:00 -2.984813     85.00          6
2021-03-28 14:36:00 -2.941003     84.80          6
2021-03-28 14:36:00 -2.941003     84.80          6
...                       ...       ...        ...
2021-03-29 18:20:00 -0.845398     74.49          7
2021-03-29 18:25:00 -0.803401     71.86          7
2021-03-29 18:25:00 -0.803401     71.86          7
2021-03-29 18:35:00 -0.695998     67.64          7
2021-03-29 19:07:00 -0.523494     61.34          7

[5789 rows x 10 columns]

In [18]:
def calculate_invalid_rate(df):
    """
    Calcule le taux d'images invalides dans un DataFrame.
    Une image est considérée invalide si :
    - 'saves' est égal à 1, ET
    - 'manual ID' n'est pas compris entre 1 et 6 (inclus), OU
    - 'radio variable' est égal à 1.
    
    :param df: DataFrame Pandas contenant les colonnes 'saves', 'manual ID' et 'radio variable'.
    :return: Le taux d'images invalides (float).
    """
    # Condition pour 'saves == 1'
    saves_condition = df['saves'] == 1
    
    # Condition pour 'manual ID' non valide
    invalid_manual_id = ~df['manual ID'].between(1, 6)
    
    # Condition pour 'radio variable == 1'
    invalid_radio_variable = df['radio variable'] == 1
    
    # Combiner les conditions (appliquer les autres conditions seulement si 'saves == 1')
    invalid_condition = saves_condition & (invalid_manual_id | invalid_radio_variable)
    
    # Nombre total d'images où 'saves == 1'
    total_saves = saves_condition.sum()
    
    # Nombre d'images invalides
    invalid_images = invalid_condition.sum()
    
    # Calcul du taux d'images invalides
    invalid_rate = invalid_images / total_saves if total_saves > 0 else 0
    
    return invalid_rate

In [19]:
for i in range(len(tempetes)):
    print(f"Tempête {i}, {calculate_invalid_rate(tempetes[i])}")

Tempête 0, 0.46674311926605505
Tempête 1, 0
Tempête 2, 0.10666666666666667
Tempête 3, 0.10133259300388672
Tempête 4, 0.26068003487358327

In [20]:
# for i in range(len(tempetes)):
#     tempetes[i] = complete_filter(tempetes[i].copy())

In [21]:
tempetes[0]

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity,manual ID
2021-03-09 12:25:00,2021.03.09_12.25.16_flake_1_cam_0.png,Aggregate,0,1,4,10.4260,NaN,-15.410800,84.10,5
2021-03-09 12:25:00,2021.03.09_12.25.23_flake_3_cam_0.png,Aucune Sélection,1,1,3,9.2167,1.16810,-15.410800,84.10,7
2021-03-09 12:25:00,2021.03.09_12.25.23_flake_3_cam_2.png,Aucune Sélection,1,1,3,10.8100,1.16810,-15.410800,84.10,7
2021-03-09 12:25:00,2021.03.09_12.25.33_flake_6_cam_0.png,Aggregate,0,1,4,10.2650,1.11150,-15.410800,84.10,5
2021-03-09 12:25:00,2021.03.09_12.25.33_flake_6_cam_2.png,Aucune Sélection,1,1,3,10.2550,1.11150,-15.410800,84.10,7
...,...,...,...,...,...,...,...,...,...,...
2021-03-09 20:23:00,2021.03.09_20.23.44_flake_121_cam_0.png,Aggregate,0,1,3,10.6590,0.48704,-2.486949,75.06,5
2021-03-09 20:27:00,2021.03.09_20.27.28_flake_123_cam_0.png,Aggregate,0,1,4,9.5623,0.65395,-2.432562,74.78,5
2021-03-09 20:27:00,2021.03.09_20.27.28_flake_123_cam_2.png,Aggregate,0,1,4,9.0658,0.65395,-2.432562,74.78,5
2021-03-09 20:27:00,2021.03.09_20.27.34_flake_124_cam_0.png,Aggregate,0,1,4,10.3900,0.84530,-2.432562,74.78,5
2021-03-09 20:27:00,2021.03.09_20.27.34_flake_124_cam_2.png,NaN,0,0,4,9.1622,0.84530,-2.432562,74.78,7

In [22]:
tempetes[1]

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity,manual ID
2021-03-13 07:29:00,2021.03.13_07.29.37_flake_443_cam_0.png,NaN,0,0,1,9.4466,0.081312,-2.701553,61.23,7
2021-03-13 07:29:00,2021.03.13_07.29.37_flake_443_cam_1.png,NaN,0,0,1,9.2257,0.081312,-2.701553,61.23,7
2021-03-13 07:29:00,2021.03.13_07.29.37_flake_443_cam_2.png,NaN,0,0,1,9.6345,0.081312,-2.701553,61.23,7
2021-03-13 07:43:00,2021.03.13_07.43.52_flake_444_cam_0.png,NaN,0,0,4,10.3460,1.042300,-2.930646,60.58,7

In [23]:
tempetes[2]

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity,manual ID
2021-03-14 10:04:00,2021.03.14_10.04.14_flake_537_cam_0.png,Aggregate,0,1,5,9.2434,0.70068,-10.04204,79.15,5
2021-03-14 10:04:00,2021.03.14_10.04.14_flake_537_cam_2.png,Aggregate,0,1,5,9.7071,0.70068,-10.04204,79.15,5
2021-03-14 10:05:00,2021.03.14_10.05.41_flake_541_cam_0.png,Aggregate,0,1,4,9.4362,NaN,-10.06263,78.97,5
2021-03-14 10:05:00,2021.03.14_10.05.41_flake_541_cam_2.png,Aggregate,0,1,4,10.8180,NaN,-10.06263,78.97,5
2021-03-14 10:07:00,2021.03.14_10.07.17_flake_542_cam_0.png,Aggregate,0,1,5,9.3618,0.51623,-10.09344,78.34,5
...,...,...,...,...,...,...,...,...,...,...
2021-03-14 11:06:00,2021.03.14_11.06.36_flake_608_cam_0.png,Aggregate,0,1,5,9.5434,0.75170,-10.32510,79.83,5
2021-03-14 11:06:00,2021.03.14_11.06.36_flake_608_cam_2.png,Aggregate,0,1,2,9.7278,0.75170,-10.32510,79.83,5
2021-03-14 11:11:00,2021.03.14_11.11.40_flake_609_cam_2.png,Aggregate,0,1,4,10.3510,0.80537,-10.35527,79.02,5
2021-03-14 11:12:00,2021.03.14_11.12.07_flake_610_cam_2.png,Aggregate,0,1,3,10.1070,0.82895,-10.35621,78.87,5
2021-03-14 11:14:00,2021.03.14_11.14.48_flake_611_cam_0.png,NaN,0,0,1,9.7797,1.07230,-10.36034,79.59,7

In [24]:
tempetes[3]

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity,manual ID
2021-03-27 02:18:00,2021.03.27_02.18.45_flake_3772_cam_0.png,Aucune Sélection,1,1,1,9.0964,0.16020,1.365920,91.1,7
2021-03-27 02:18:00,2021.03.27_02.18.45_flake_3772_cam_2.png,NaN,0,1,1,9.1816,0.16020,1.365920,91.1,7
2021-03-27 02:21:00,2021.03.27_02.21.21_flake_3773_cam_0.png,Aggregate,0,1,4,9.2676,2.80600,1.236691,92.3,5
2021-03-27 02:21:00,2021.03.27_02.21.21_flake_3773_cam_1.png,Aggregate,0,1,4,9.5605,2.80600,1.236691,92.3,5
2021-03-27 02:21:00,2021.03.27_02.21.21_flake_3773_cam_2.png,Aggregate,0,1,4,9.0488,2.80600,1.236691,92.3,5
...,...,...,...,...,...,...,...,...,...,...
2021-03-27 09:02:00,2021.03.27_09.02.47_flake_6717_cam_1.png,Aggregate,0,1,4,10.2960,0.87182,-2.687584,90.6,5
2021-03-27 09:02:00,2021.03.27_09.02.47_flake_6717_cam_2.png,NaN,0,0,4,9.4255,0.87182,-2.687584,90.6,7
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_0.png,NaN,0,0,4,10.6690,0.92324,-2.714185,90.5,7
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_1.png,NaN,0,0,4,10.5100,0.92324,-2.714185,90.5,7
2021-03-27 09:04:00,2021.03.27_09.04.00_flake_6718_cam_2.png,NaN,0,0,4,10.2180,0.92324,-2.714185,90.5,7

In [25]:
tempetes[4]

,file,hydrometeor,radio variable,saves,label ID,xhi,fallspeed,Air_Temp,Humidity,manual ID
2021-03-28 14:33:00,2021.03.28_14.33.09_flake_6753_cam_0.png,Aggregate,0,1,5,9.9952,0.084466,-2.984813,85.00,5
2021-03-28 14:33:00,2021.03.28_14.33.09_flake_6753_cam_1.png,Graupel,0,1,5,9.2024,0.084466,-2.984813,85.00,6
2021-03-28 14:33:00,2021.03.28_14.33.09_flake_6753_cam_2.png,Graupel,0,1,5,10.0430,0.084466,-2.984813,85.00,6
2021-03-28 14:36:00,2021.03.28_14.36.08_flake_6755_cam_0.png,Graupel,0,1,5,10.1720,1.583900,-2.941003,84.80,6
2021-03-28 14:36:00,2021.03.28_14.36.08_flake_6755_cam_1.png,Graupel,0,1,5,9.9375,1.583900,-2.941003,84.80,6
...,...,...,...,...,...,...,...,...,...,...
2021-03-29 18:20:00,2021.03.29_18.20.29_flake_4814_cam_2.png,NaN,0,0,5,9.7379,0.085907,-0.845398,74.49,7
2021-03-29 18:25:00,2021.03.29_18.25.12_flake_4816_cam_1.png,NaN,0,0,5,9.0082,0.109680,-0.803401,71.86,7
2021-03-29 18:25:00,2021.03.29_18.25.12_flake_4816_cam_2.png,NaN,0,0,5,9.8941,0.109680,-0.803401,71.86,7
2021-03-29 18:35:00,2021.03.29_18.35.25_flake_4820_cam_0.png,NaN,0,0,5,9.1147,1.284400,-0.695998,67.64,7
2021-03-29 19:07:00,2021.03.29_19.07.23_flake_4822_cam_2.png,NaN,0,0,1,10.4970,1.995000,-0.523494,61.34,7

In [26]:
# Matrices de confusion pour les classements complétés
def confusion_matrix(df, col1, col2):
    """
    Crée une matrice de confusion à partir de deux colonnes d'un DataFrame.
    
    :param df: Le DataFrame contenant les données.
    :param col1: Nom de la colonne pour les valeurs réelles.
    :param col2: Nom de la colonne pour les prédictions.
    :return: Une matrice de confusion sous forme de DataFrame.
    """
    # Générer la matrice de confusion
    confusion_matrix = pd.crosstab(df["manual ID"], df["label ID "], rownames=['Actual'], colnames=['Predicted'], dropna=False)
    
    # Ajouter des valeurs manquantes pour s'assurer que toutes les valeurs de 1 à 6 sont incluses
    index = range(1, 7)  # Valeurs possibles
    confusion_matrix = confusion_matrix.reindex(index=index, columns=index, fill_value=0)
    
    return confusion_matrix

In [27]:
conf_matrix = confusion_matrix(tempetes[0], 'Actual', 'Predicted')
print(conf_matrix)

Predicted  1  2   3    4   5  6
Actual
1          0  0   0    0   0  0
2          1  0   1    1   0  0
3          0  1   4    1   0  0
4          0  0   0    0   0  0
5          9  7  20  407  10  0
6          0  0   1    1   1  0

In [28]:
conf_matrix = confusion_matrix(tempetes[3], 'Actual', 'Predicted')
print(conf_matrix)

Predicted    1   2    3     4    5   6
Actual
1           20   0    0     0    1   1
2            0   1    0     0    0   0
3            1   0    0     3    0   0
4            0   0    0     0    0   0
5          217  18  202  2349  257  30
6            4   0    6    15  112   0

In [29]:
conf_matrix = confusion_matrix(tempetes[4], 'Actual', 'Predicted')
print(conf_matrix)

Predicted   1  2   3    4    5  6
Actual
1           0  0   0    0    0  0
2           2  9   0    0    0  0
3           0  1   2    2    2  0
4           0  0   0    0    0  0
5          36  8  16  143   68  2
6          20  9   3   17  508  0