In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from PIL import Image
from icecream import ic
from datetime import datetime

# Fonctions

In [2]:
#Remplacer ".mat" par ".png" dans le dataframe contenant les noms de fichiers

def mat_to_png(filename):
    return filename.replace(".mat",".png")

In [3]:
#Obtenir un datetime en fonction du nom de fichier

def filename_to_datetime(filename):
    #Assume format AAAA.MM.DD_HH.MM.SS_flake_x_cam_y.png
    #Change filename to datetime
    time = filename.split("_")[0]+"_"+filename.split("_")[1]
    timeformat = '%Y.%m.%d_%H.%M.%S'
    dt_object = datetime.strptime(time, timeformat)
    return dt_object

In [4]:
#Obtenir un chemin relatif en fonction du nom de fichier

def path_from_filename(filename):
    path= "" # TODO
    filename = filename.replace('.png ','')
    timestamp = filename[0:18]
    month_file = timestamp[0:4]+"_"+timestamp[5:7]+"/"
    day_file = ".".join(timestamp[0:10].split("-"))+"/"
    hour = timestamp[11:13]+"/"
    
    return path+month_file+day_file+hour+filename+'.png'

# Uniformiser les données de mars et avril

In [5]:
#---
# On a besoin du path vers tous les DFs
#---
path_SJ="../../../SAJESS/SJ_MASC_Data/MatLab_csv_files/"

## MARS

In [6]:

#---
# DONNÉES EN MARS
#---
march_data="X_March.csv"
march_columns="Xlab_March.csv"
march_names="Xname_March.csv"

In [7]:
#---
# DATAFRAME - MARS
#---

#Extraire les noms de colonnes
march_df_names = pd.read_csv(path_SJ+march_columns, header=None)

#Créer le dataframe pour mars
march_df = pd.read_csv(path_SJ+march_data, names = march_df_names[0].tolist())

#Créer l'index et ajouter les noms de fichiers png pour mars
march_df_index = pd.read_csv(path_SJ+march_names, header=None)

In [8]:
#---
# MODIFICATIONS INDEX & COLONNES - MARS
#---

#Choix de l'index
march_df.index = march_df_index[0].apply(filename_to_datetime)

#Formattage de l'index
march_df.index=pd.to_datetime(march_df.index)
march_df.index.name = 'timestamp'

#Ajout des noms de fichier au dataframe
march_df['file']=march_df_index[0].values
march_df['file']=march_df['file'].apply(mat_to_png)

#Ajout des colonnes nécessaires pour le MASC MVP APP
# TODO
march_df['hydrometeor']=""
march_df['radio variable']=0
march_df['saves']=0

#Modification de l'ordre des colonnes
new_columns_order = ['file']+['hydrometeor']+['radio variable']+['saves']+[
    col for col in march_df.columns if col not in ['file','hydrometeor','radio variable','saves']]
march_df = march_df[new_columns_order]

In [9]:
#Vérification de l'état du dataframe
march_df

,file,hydrometeor,radio variable,saves,label ID,area,Dmax,Dmean,complex,xhi,...,max_intens,number of ROIs detected,area ratio/ roundness,AR D90,AR Rect,AR E_out,orientation Dmax,orientation Rect,flake ID,new uniqueID
timestamp,,,,,,,,,,,,,,,,,,,,,
2021-03-04 16:06:59,2021.03.04_16.06.59_flake_1_cam_0.png,,0,0,4,24901.0,345.090,261.5,3.34120,10.1810,...,0.666670,9,0.26125,0.50000,0.48793,0.47938,81.165,1.36070,1,1
2021-03-04 16:06:59,2021.03.04_16.06.59_flake_1_cam_1.png,,0,0,4,27929.0,335.120,257.5,3.18350,9.9025,...,1.000000,5,0.31389,0.52976,0.52589,0.54442,88.461,1.53480,1,1
2021-03-04 16:06:59,2021.03.04_16.06.59_flake_1_cam_2.png,,0,0,4,39442.0,410.840,326.5,9.52530,12.7310,...,0.690200,32,0.29577,0.63835,0.56883,0.60363,72.579,1.50890,1,1
2021-03-04 16:12:22,2021.03.04_16.12.22_flake_2_cam_0.png,,0,0,2,68.0,26.000,18.0,1.94990,9.6924,...,0.156860,8,0.12789,0.23077,0.18790,0.34726,22.620,0.42663,2,2
2021-03-04 16:12:22,2021.03.04_16.12.22_flake_2_cam_1.png,,0,0,1,73.0,23.770,17.5,1.78290,9.8066,...,0.345100,5,0.15302,0.34783,0.24752,0.45582,14.621,0.35877,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-29 18:35:25,2021.03.29_18.35.25_flake_4820_cam_2.png,,0,0,5,100.0,11.705,11.5,0.90270,8.9155,...,0.117650,59,0.89882,1.00000,0.90909,0.94351,70.017,1.57080,4820,3333
2021-03-29 18:44:08,2021.03.29_18.44.08_flake_4821_cam_0.png,,0,0,5,501.0,26.833,25.5,0.92002,8.2431,...,0.286270,1,0.85214,0.92857,0.96000,0.90526,63.435,1.57080,4821,3334
2021-03-29 18:44:08,2021.03.29_18.44.08_flake_4821_cam_1.png,,0,0,5,474.0,26.420,25.5,0.91995,8.3423,...,0.294120,1,0.85397,0.92593,0.93671,0.90021,60.524,0.32175,4821,3334
2021-03-29 18:44:08,2021.03.29_18.44.08_flake_4821_cam_2.png,,0,0,5,707.0,31.906,30.5,0.94422,8.5195,...,0.341180,1,0.84192,0.87879,0.96667,0.93195,-32.196,0.00000,4821,3334
2021-03-29 19:07:23,2021.03.29_19.07.23_flake_4822_cam_2.png,,0,0,1,52.0,13.601,12.5,2.34720,10.4970,...,0.058824,1,0.33633,0.78571,0.67568,0.73402,-53.973,0.54042,4822,3335

In [10]:
# 21 août 24 - Ajout d'un filtre pour qualité photo, reprise des dataframe
filtered_march_df = march_df[march_df['xhi '] >= 9]
filtered_march_df

,file,hydrometeor,radio variable,saves,label ID,area,Dmax,Dmean,complex,xhi,...,max_intens,number of ROIs detected,area ratio/ roundness,AR D90,AR Rect,AR E_out,orientation Dmax,orientation Rect,flake ID,new uniqueID
timestamp,,,,,,,,,,,,,,,,,,,,,
2021-03-04 16:06:59,2021.03.04_16.06.59_flake_1_cam_0.png,,0,0,4,24901.0,345.090,261.5,3.34120,10.1810,...,0.666670,9,0.26125,0.50000,0.48793,0.47938,81.1650,1.36070,1,1
2021-03-04 16:06:59,2021.03.04_16.06.59_flake_1_cam_1.png,,0,0,4,27929.0,335.120,257.5,3.18350,9.9025,...,1.000000,5,0.31389,0.52976,0.52589,0.54442,88.4610,1.53480,1,1
2021-03-04 16:06:59,2021.03.04_16.06.59_flake_1_cam_2.png,,0,0,4,39442.0,410.840,326.5,9.52530,12.7310,...,0.690200,32,0.29577,0.63835,0.56883,0.60363,72.5790,1.50890,1,1
2021-03-04 16:12:22,2021.03.04_16.12.22_flake_2_cam_0.png,,0,0,2,68.0,26.000,18.0,1.94990,9.6924,...,0.156860,8,0.12789,0.23077,0.18790,0.34726,22.6200,0.42663,2,2
2021-03-04 16:12:22,2021.03.04_16.12.22_flake_2_cam_1.png,,0,0,1,73.0,23.770,17.5,1.78290,9.8066,...,0.345100,5,0.15302,0.34783,0.24752,0.45582,14.6210,0.35877,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-29 18:20:29,2021.03.29_18.20.29_flake_4814_cam_2.png,,0,0,5,1521.0,55.027,48.0,1.04880,9.7379,...,1.000000,2,0.62762,0.78571,0.93867,0.81513,-70.9070,0.51915,4814,3327
2021-03-29 18:25:12,2021.03.29_18.25.12_flake_4816_cam_1.png,,0,0,5,812.0,41.231,36.0,1.01970,9.0082,...,0.662750,1,0.58352,0.61905,0.59562,0.58138,39.0940,0.61073,4816,3329
2021-03-29 18:25:12,2021.03.29_18.25.12_flake_4816_cam_2.png,,0,0,5,837.0,40.608,36.0,1.02380,9.8941,...,0.890200,1,0.62996,0.71429,0.89796,0.74075,9.9262,0.78540,4816,3329
2021-03-29 18:35:25,2021.03.29_18.35.25_flake_4820_cam_0.png,,0,0,5,312.0,24.331,22.5,0.95823,9.1147,...,0.686270,44,0.63467,0.80000,0.94815,0.73269,-9.4623,1.00410,4820,3333
2021-03-29 19:07:23,2021.03.29_19.07.23_flake_4822_cam_2.png,,0,0,1,52.0,13.601,12.5,2.34720,10.4970,...,0.058824,1,0.33633,0.78571,0.67568,0.73402,-53.9730,0.54042,4822,3335

## AVRIL

In [11]:
#---
# DONNÉES EN AVRIL
#---
april_data="X_April.csv"
april_columns="Xlab_April.csv"
april_names="Xname_April.csv"

In [12]:
#---
# DATAFRAME - APRIL
#---

# Extraire les noms de colonnes
april_df_names = pd.read_csv(path_SJ + april_columns, header=None)

# Créer le dataframe pour avril
april_df = pd.read_csv(path_SJ + april_data, names=april_df_names[0].tolist())

# Créer l'index et ajouter les noms de fichiers png pour avril
april_df_index = pd.read_csv(path_SJ + april_names, header=None)

In [13]:
#---
# MODIFICATIONS INDEX & COLONNES - APRIL
#---

# Choix de l'index
april_df.index = april_df_index[0].apply(filename_to_datetime)

# Formattage de l'index
april_df.index = pd.to_datetime(april_df.index)
april_df.index.name = 'timestamp'

# Ajout des noms de fichier au dataframe
april_df['file'] = april_df_index[0].values
april_df['file'] = april_df['file'].apply(mat_to_png)

# Ajout des colonnes nécessaires pour le MASC MVP APP
april_df['hydrometeor'] = ""
april_df['radio variable'] = 0
april_df['saves'] = 0

# Modification de l'ordre des colonnes
new_columns_order = ['file'] + ['hydrometeor'] + ['radio variable'] + ['saves'] + [
    col for col in april_df.columns if col not in ['file', 'hydrometeor', 'radio variable', 'saves']]
april_df = april_df[new_columns_order]

In [14]:
# Vérification de l'état du dataframe
april_df

,file,hydrometeor,radio variable,saves,label ID,area,Dmax,Dmean,complex,xhi,...,max_intens,number of ROIs detected,area ratio/ roundness,AR D90,AR Rect,AR E_out,orientation Dmax,orientation Rect,flake ID,new uniqueID
timestamp,,,,,,,,,,,,,,,,,,,,,
2021-04-01 07:42:05,2021.04.01_07.42.05_flake_1_cam_0.png,,0,0,1,60,10.8170,9.5,1.01970,9.5545,...,0.32549,5,0.58765,0.72727,0.88889,0.62103,-56.310,1.57080,1,1
2021-04-01 07:42:05,2021.04.01_07.42.05_flake_1_cam_1.png,,0,0,1,99,11.4020,11.5,0.87890,9.2946,...,0.81176,5,0.94492,0.91667,0.90909,0.93987,74.745,1.57080,1,1
2021-04-01 07:42:05,2021.04.01_07.42.05_flake_1_cam_2.png,,0,0,1,64,8.9443,9.0,0.84628,9.6988,...,1.00000,4,0.99305,0.90909,1.00000,0.94310,63.435,1.57080,1,1
2021-04-01 07:44:08,2021.04.01_07.44.08_flake_2_cam_0.png,,0,0,1,152,17.0290,16.0,1.00680,9.2805,...,0.38431,2,0.60856,0.72222,0.62887,0.76879,-40.236,0.90975,2,2
2021-04-01 07:44:08,2021.04.01_07.44.08_flake_2_cam_1.png,,0,0,5,195,15.8110,15.5,0.88885,9.4830,...,1.00000,2,0.94738,0.94118,0.93333,0.95166,71.565,1.57080,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-22 05:47:30,2021.04.22_05.47.30_flake_7123_cam_0.png,,0,0,5,510,35.1280,28.0,1.01180,8.4307,...,0.32549,1,0.51937,0.55556,0.52919,0.52619,85.101,1.43820,7123,1177
2021-04-22 05:47:31,2021.04.22_05.47.31_flake_7124_cam_0.png,,0,0,5,503,35.2280,27.5,1.04400,8.4740,...,0.32549,1,0.48499,0.54054,0.51429,0.51502,83.480,1.57080,7124,1178
2021-04-22 05:47:51,2021.04.22_05.47.51_flake_7125_cam_0.png,,0,0,5,497,35.1280,27.5,1.02490,8.4425,...,0.30980,1,0.48014,0.52778,0.51174,0.50266,85.101,1.40560,7125,1179
2021-04-22 07:04:48,2021.04.22_07.04.48_flake_7369_cam_2.png,,0,0,1,267,23.7700,20.0,1.12220,9.3413,...,0.16471,1,0.54008,0.68000,0.65217,0.72945,-14.621,0.00000,7369,1180
2021-04-22 07:04:49,2021.04.22_07.04.49_flake_7370_cam_2.png,,0,0,1,230,22.5610,18.5,1.09740,9.1590,...,0.12941,1,0.52816,0.60870,0.59091,0.72239,-12.804,0.00000,7370,1181

In [15]:
filtered_april_df = april_df[april_df['xhi '] >= 9]
filtered_april_df

,file,hydrometeor,radio variable,saves,label ID,area,Dmax,Dmean,complex,xhi,...,max_intens,number of ROIs detected,area ratio/ roundness,AR D90,AR Rect,AR E_out,orientation Dmax,orientation Rect,flake ID,new uniqueID
timestamp,,,,,,,,,,,,,,,,,,,,,
2021-04-01 07:42:05,2021.04.01_07.42.05_flake_1_cam_0.png,,0,0,1,60,10.8170,9.5,1.01970,9.5545,...,0.325490,5,0.58765,0.72727,0.88889,0.62103,-56.310,1.57080,1,1
2021-04-01 07:42:05,2021.04.01_07.42.05_flake_1_cam_1.png,,0,0,1,99,11.4020,11.5,0.87890,9.2946,...,0.811760,5,0.94492,0.91667,0.90909,0.93987,74.745,1.57080,1,1
2021-04-01 07:42:05,2021.04.01_07.42.05_flake_1_cam_2.png,,0,0,1,64,8.9443,9.0,0.84628,9.6988,...,1.000000,4,0.99305,0.90909,1.00000,0.94310,63.435,1.57080,1,1
2021-04-01 07:44:08,2021.04.01_07.44.08_flake_2_cam_0.png,,0,0,1,152,17.0290,16.0,1.00680,9.2805,...,0.384310,2,0.60856,0.72222,0.62887,0.76879,-40.236,0.90975,2,2
2021-04-01 07:44:08,2021.04.01_07.44.08_flake_2_cam_1.png,,0,0,5,195,15.8110,15.5,0.88885,9.4830,...,1.000000,2,0.94738,0.94118,0.93333,0.95166,71.565,1.57080,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-22 05:22:06,2021.04.22_05.22.06_flake_7006_cam_0.png,,0,0,1,95,21.0950,17.5,1.82340,9.0945,...,0.082353,1,0.22927,0.63636,0.54179,0.67408,-58.570,1.13420,7006,1061
2021-04-22 05:22:08,2021.04.22_05.22.08_flake_7007_cam_0.png,,0,0,1,109,21.0950,18.0,2.59390,9.4952,...,0.074510,1,0.30885,0.77273,0.70807,0.91681,-58.570,1.38540,7007,1062
2021-04-22 05:22:39,2021.04.22_05.22.39_flake_7009_cam_0.png,,0,0,1,92,20.1250,17.0,1.64700,9.0115,...,0.078431,1,0.28488,0.61905,0.56757,0.86876,-63.435,1.13420,7009,1064
2021-04-22 07:04:48,2021.04.22_07.04.48_flake_7369_cam_2.png,,0,0,1,267,23.7700,20.0,1.12220,9.3413,...,0.164710,1,0.54008,0.68000,0.65217,0.72945,-14.621,0.00000,7369,1180
2021-04-22 07:04:49,2021.04.22_07.04.49_flake_7370_cam_2.png,,0,0,1,230,22.5610,18.5,1.09740,9.1590,...,0.129410,1,0.52816,0.60870,0.59091,0.72239,-12.804,0.00000,7370,1181

## DATAFRAME POUR CHAQUE TEMPÊTE DE NEIGE

### FONCTIONS

In [16]:
#Extraire en tuple le timestamp de début et de fin d'une tempête à partir d'un df donné
def timeframe(storm,storm_df):
    start=pd.to_datetime(storm_df['start'][storm])
    end=pd.to_datetime(storm_df['end'][storm])
    return (start,end)

In [17]:
#Générer une section de dataframe en fonction de l'intervalle de la tempête choisie
def dataframe_from_storm_timeframe(storm,masc_df):
    start = storm[0]
    end = storm[1]
    storm_mdf = masc_df[(masc_df.index >= start) & (masc_df.index <= end)]
    return storm_mdf.copy()

In [18]:

def identify_month(dt):
    """
    Identifies the month from a datetime object.
    
    Parameters:
    dt (string): A timestamp
    
    Returns:
    str: The name of the month
    """
    month_list = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

    month = month_list[ int(dt.split('-')[1]) -1]
    
    
    return month

### Création des dataframes propres à chaque tempête

In [19]:
#---
# IMPORTER LA LISTE DES TEMPÊTES
#---
path_stormDates = "../../codes_export/dataframe/ETE24/Snowstorms_For_MASC_Validation.csv"
stormDates_df = pd.read_csv(path_stormDates)
stormDates_df.index.name = 'storm number'
stormDates_df=stormDates_df.drop("Unnamed: 0", axis=1)

print(stormDates_df)

                            start                  end type   Temp_min  \
storm number
0             2021-03-09 11:10:00  2021-03-09 20:40:00   SN -16.153020
1             2021-03-13 05:40:00  2021-03-13 08:50:00   SN  -3.861495
2             2021-03-14 10:00:00  2021-03-14 12:40:00   SN -10.375430
3             2021-03-27 02:10:00  2021-03-27 09:20:00   SN  -2.779660
4             2021-03-28 12:10:00  2021-03-29 19:30:00   SN  -4.692759
5             2021-04-01 11:10:00  2021-04-02 00:50:00   SN  -3.727957
6             2021-04-02 15:30:00  2021-04-02 20:50:00   SN  -4.316516
7             2021-04-21 21:00:00  2021-04-23 09:00:00   SN  -2.469386

              Temp_max  Temp_mean
storm number
0            -2.235767  -8.117721
1            -1.357761  -2.579345
2            -9.007304 -10.036219
3             1.526459  -0.703188
4             2.765668  -0.733800
5             0.831890  -0.804353
6            -3.325047  -3.699031
7             0.634999  -1.199461

In [20]:
# Créer les dataframes propres à chaque tempête
for i in stormDates_df.index:
    stormTimeframe = timeframe(i, stormDates_df)
    month = identify_month(str(stormTimeframe[0]))
    
    if month == 'March':
        temporary_dataframe = dataframe_from_storm_timeframe( stormTimeframe,filtered_march_df )
        df_filename = f"march_storm0{i}_df.csv"
        temporary_dataframe.to_csv("../../codes_export/dataframe/ETE24/phase1_SN/MVP_setup_dataframes/march/"+"filtered_"+df_filename)
        
    elif month == 'April':
        temporary_dataframe = dataframe_from_storm_timeframe( stormTimeframe,filtered_april_df )
        df_filename = f"april_storm0{i}_df.csv"
        temporary_dataframe.to_csv("../../codes_export/dataframe/ETE24/phase1_SN/MVP_setup_dataframes/april/"+"filtered_"+df_filename)